[package]
name = "mp4-rotator"
version = "0.1.0"
authors = ["André Hänsel <haensel@creations.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "*"
arrayvec = "*"

[profile.release]
lto = true